mui/dockwidgets/hook_list_widget.py, mui/manticore_native_runner.py, mui/mui.py, mui/notification.py
Closes https://github.com/trailofbits/ManticoreUI/issues/40
Currently functionality just lists the find/avoid/custom hooks, and double clicking navigates the user to the specific hook.
Relocating the PIE handling to the runner also fixes an issue with hooks not getting highlighted in PIE binaries.
=> Add hook list widget

binjastub/requirements.txt, requirements-dev.txt
just a tiny fix - `git://` should no longer be used as of Jan 11 2022, see: https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
PR just changes the protocol to `https://`
This error will be shown if `git://` is used:
```
Cloning git://github.com/trailofbits/manticore.git (to revision a16a01148bde965803cc3a2101bf4e03b0dfe340) to /tmp/pip-req-build-0d7jvv1_
Running command git clone -q git://github.com/trailofbits/manticore.git /tmp/pip-req-build-0d7jvv1_
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
=> pip install manticore with a non-deprecated git protocol

README.rst, mui/manticore_native_runner.py, mui/settings.py
Adds native run option to use unicorn to emulate the binary until a certain address.
This significantly speeds up the startup time for manticore.
Preview:
=> Add option to unicorn emulate until address

mui/dockwidgets/global_hook_dialog.py, mui/dockwidgets/hook_list_widget.py, mui/dockwidgets/library_dialog.py, mui/hook_manager.py, mui/manticore_native_runner.py, mui/mui.py, mui/native_plugin.py, mui/notification.py, mui/settings.py
This PR implements a new feature that allows MUI users to add bndb files of shared libraries used by the binaries (i.e. libc) to the project. The MUI hooks from these external bndbs will be extracted and added when MUI solve is run. This allows us to have "multi-file" projects.
Summary of code changes:
- Refactor of hook management code to decouple code from directly managing session data 
- Additional command `MUI - Manage Shared Library BNDBs`
- Additional dialog that allows adding and deletion of shared library bndbs
=> Add shared library MUI hook support

mui/mui.py, mui/settings.py
As per https://github.com/trailofbits/ManticoreUI/issues/54, adds a text field in the run dialog that allows users to write, CLI-style, any additional manticore arguments they want. 
Mimics behaviour in the Ghidra plugin and uses the existing protobuf attribute made for this purpose.
Another small side-effect is that the options in the RunDialog now also work except for those denoted in the UI as "unsupported"
=> Server Integration: Specify arbitrary arguments, CLI-style

mui/dockwidgets/state_list_widget.py, mui/manticore_native_runner.py, mui/utils.py
Closes https://github.com/trailofbits/ManticoreUI/issues/69.
Summary of changes:
1. Refactor of state pause code. More generic API that allows `MUIState` to add callbacks to states based on `state_id`. The callbacks can be removed at runtime unlike manticore hooks.
2. Added `Kill` option to kill states
3. Small quality of life changes to make state list a bit more friendly for right-clicking
=> Add manual state killing support

mui/manticore_native_runner.py
Something changed in binja that changed the behaviour of the code we use to check for whether a binary is PIE-enabled.
pre 3.1
```py
h_addr = bv.symbols["__elf_header"][0].address
h_type = bv.types["Elf64_Header"]
header = TypedDataAccessor(h_type, h_addr, bv, Endianness.LittleEndian)
header["type"].value
>>> 3
```
3.1
```py
h_addr = bv.symbols["__elf_header"][0].address
h_type = bv.types["Elf64_Header"]
header = TypedDataAccessor(h_type, h_addr, bv, Endianness.LittleEndian)
header["type"].value
>>> <ET_DYN = 0x3>
```
This fix should allow the code to work on both versions.
=> Fix breaking changes from Binary Ninja 3.1

plugins/ghidra/README.rst
Just a small PR because the old links were using markdown format instead of rst link format.
=> Fix Ghidra README links

plugins/ghidra/MUI/src/main/java/mui/MUIHookCodeDialogLauncher.java, plugins/ghidra/MUI/src/main/java/mui/MUIHookListComponent.java, plugins/ghidra/MUI/src/main/java/mui/MUIHookUserObject.java, plugins/ghidra/MUI/src/main/java/mui/MUIPlugin.java, plugins/ghidra/MUI/src/main/java/mui/MUIPopupMenu.java
This PR adds 2 main features:
- Right-clicking on custom/global hooks in the hook list now shows an additional option to edit the hook, which launches the code editor and allows you to edit the hook's function code
- Double-clicking custom/find/avoid hooks in the hook list with jump to that address in the Listing component
Also, 1 minor change:
- hook list now shows hook names (addresses for find/avoid/custom, timestamp for global)
Also, 1 bit of refactoring:
- the Custom/Global Hook Code Editor Dialog is now delegated to a class of its own
=> [Ghidra] Edit Hook and Jump to Address via HookList

server/muicore/MUICore.proto, server/muicore/MUICore_pb2.py, server/muicore/MUICore_pb2.pyi, server/muicore/mui_server.py
Super quick PR which closes #87
Adds `optional` to fields that may be optional (doesn't apply to `repeated` fields), which improves readability and allows us to use the HasField methods in future instead of relying on a weird default value to indicate an unset field (eg. the state descriptor's `parent_id`, which was changed here)
~~Also, fixes a bug where `ContextFilter` was previously called `ManticoreContextFilter` (I'm a bit confused because this definitely used to work, but the manticore repo git blame suggests that it's been 5 years since the last change)~~ oops it's late and I was using the wrong venv 😪
=> [Server] Add explicit field presence

.github/workflows/binaryninja-ci.yml, plugins/binaryninja/requirements-dev.txt
Fixes the CI issue as described in Slack - binja-integration will no longer affect the cached venv
=> Binja CI excludes binja-integration branch

.github/workflows/binaryninja-ci.yml, plugins/binaryninja/mui/dockwidgets/hook_list_widget.py, plugins/binaryninja/mui/hook_manager.py, plugins/binaryninja/mui/manticore_native_runner.py, plugins/binaryninja/mui/mui.py, plugins/binaryninja/mui/native_plugin.py, plugins/binaryninja/mui/notification.py, plugins/binaryninja/mui/settings.py, plugins/binaryninja/requirements-dev.txt, plugins/binaryninja/tests/test_hook_manager.py, plugins/binaryninja/tests/test_native_plugin.py, plugins/binaryninja/tests/test_persistence.py
Closes #83
- Custom hooks are now identified by `name` though the address can be easily retrieved by `int(name[:-3], 16)`
- Name is just address_XX where XX denotes the id of the hook created at that address, similar to the numbering system for Global Hooks
- Additionally, right-clicking on a custom or global hook in the Hook List shows an Edit option which allows you to directly edit the hook code (mimics implementation in https://github.com/trailofbits/ManticoreUI/pull/77)
=> [Binja] Multiple custom hooks can be created at same address 

plugins/binaryninja/binjastub/requirements.txt
Fixes two issues:
1. Missing `__init__.py` in common that causes import errors for binja
2. Protobuf error when running manticore (was pegged to old commit without the protobuf change)
=> [Binja] Bugfixes

server/muicore/MUICore.proto, server/muicore/MUICore_pb2.py, server/muicore/MUICore_pb2.pyi, server/muicore/MUICore_pb2_grpc.py, server/muicore/mui_server.py, server/tests/test_native.py
First of 3 PRs meant to demonstrate the process of adding a feature to the MUI Plugins - first by implementing Manticore functionality in the MUI Server and then making UI changes on the respective plugin frontends.
This PR adds support for manual state pausing and killing. Closes #85.
Commit messages have been written & rebased to be descriptive, but an overview of what's done here is:
1. Adding a new rpc and modifying an existing rpc request message in the protocol buffer spec (`MUICore.proto`)
2. Generating Python files and stubs with `just generate`
3. Implementing the actual functionality by interacting with the Manticore API in `mui_server.py`
4. Writing new tests
=> [Server] Support manual state control (Pause/Kill)

plugins/ghidra/MUI/src/main/grpc/muicore/ManticoreUIGrpc.java, plugins/ghidra/MUI/src/main/java/mui/MUIStateListProvider.java, plugins/ghidra/MUI/src/main/java/mui/ManticoreRunner.java, plugins/ghidra/MUI/src/main/java/muicore/MUICore.java, plugins/ghidra/MUI/src/main/proto/MUICore.proto
Second of 3 PRs meant to demonstrate the process of adding a feature to the MUI Plugins - first by implementing Manticore functionality in the MUI Server and then making UI changes on the respective plugin frontends.
This PR is reliant on #96 being merged in first, and implements the necessary UI and "connector" changes to the Ghidra plugin frontend so that the Ghidra plugin can use the newly-implemented ControlState rpc to support manual state pausing and killing.
Commit messages have been written & rebased to be descriptive, but an overview of what's done here is:
1. Fetching the newly-updated protocol buffer spec from #96
2. Generating Java files from the protocol buffer spec with `gradle buildExtension`
3. Adding a function to call the ControlState rpc in the "connector" class …
=> [Ghidra] Support manual state control (Pause/Kill)

plugins/binaryninja/mui/native_plugin.py, plugins/binaryninja/tests/test_native_plugin.py
Adds tests for `TraceBlockPlugin` which saves a basic-block trace for manticore states.
Fix bug in `TraceBlockPlugin` causing tests to fail.
=> [Binja] Add TraceBlockPlugin tests

docs/binaryninja/evm.rst, docs/binaryninja/function_models.rst, docs/binaryninja/hooks.rst, docs/binaryninja/shared_library.rst, docs/binaryninja/state_management.rst, docs/features.rst, docs/ghidra/hooks.rst
Adds a new /docs directory containing more detailed documentation on features. This is meant to supplement what we current have in the respective READMEs.
The `features.rst` doc is the central doc that links to all other documentations.
=> Add Documentation

.github/workflows/binaryninja-ci.yml, .github/workflows/ghidra-ci.yml, .github/workflows/server-ci.yml
There is a bug in CI causing the binja workflow not to run (the Actions tab shows a bunch of CI startup failures)
The fix is that the `ubuntu-20.04` in the binja workflow matrix needs to be in square brackets. That said, there is no longer a need for a matrix, so this PR fixes that bug and allows binja CI to run again and simplifies the workflow.
Additionally, we used to have to make dummy commits in the respective plugin/server directories to get CI to run if we were only editing the workflow. This PR also makes CI run if the workflow itself has been modified.
=> Fix bug in CI, run CI when workflow is modified

plugins/binaryninja/binjastub/__init__.py
Cleans up the code to make sure we can install using the plugin manager.
To test:
1. (shell) `mkdir ~/.binaryninja/repositories/test`
2. (optional) setup virtualenv settings in Binary Ninja if need be
3. Run the following inside Binary Ninja python interpreter
```py
mgr = RepositoryManager()
mgr.add_repository("https://raw.githubusercontent.com/lordidiot/community-plugins/master/plugins.json", "test")
mgr.check_for_updates()
```
4. `Manage Plugins` in Binary Ninja, search for `ManticoreUI` in the page
5. Click `Install` followed by `Enable`
=> [Binja] Fix plugin manager install

plugins/binaryninja/binjastub/requirements.txt
Two changes:
1. Bumps manticore version to use https://github.com/trailofbits/manticore/commit/04cc68dbf164af976df23e3a435207aa8fcb246d
2. Specifies `[native]` optional dependency for manticore so that we don't have to manually add native dependencies
=> [Binja] Cleanup requirements.txt
